version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - ls -al
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "package*.json"
    - "public/**/*"
    - ".next/**/*"
    - "next.config.js"
